# Site settings
title: Mythical Robotics
description: > # this means to ignore newlines until "baseurl:"
  Mythical Robotics is a consortium of FIRST teams from Avalon School and Great River School.
   It currently encompases one FIRST Robotics team, one FIRST Tech Challenge team, and five FIRST Lego League Teams.
baseurl: "http://lauraschultz.github.io/mythicalrobotics" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
port: 2000
