# Site settings
title: Mythical Robotics
description: > # this means to ignore newlines until "baseurl:"
  Mythical Robotics is a consortium of FIRST teams from Avalon School and Great River School.
   It currently encompases one FIRST Robotics team, one FIRST Tech Challenge team, and five FIRST Lego League Teams.
baseurl: "http://lauraschultz.github.io/mythicalrobotics" # the subpath of your site, e.g. /blog/

# LEGO LEAGUE:
team1_name: "12345 Team Athena"
team1_url: team-athena

team2_name: "12345 Team 1"
team2_url: team-1

team3_name: "12345 Team 2"
team3_url: team-2

team4_name: "12345 The Brickheads"
team4_url: the-brickheads

team5_name: "12345 Avalon Team"
team5_url: avalon-team

# Build settings
markdown: kramdown