# Site settings
title: Mythical Robotics
description: > # this means to ignore newlines until "baseurl:"
  Mythical Robotics is a consortium of FIRST teams from Avalon School and Great River School.
   It currently encompases one FIRST Robotics team, one FIRST Tech Challenge team, and five FIRST Lego League Teams.
baseurl: "http://www.mythicalrobotics.com" # the subpath of your site, e.g. /blog/

# LEGO LEAGUE:
team1_name: "Team Athena"
team1_url: team-athena

team2_name: "GRS - FLL"
team2_url: grs-fll

team3_name: "Avalon FLL"
team3_url: avalon-fll

# Build settings
markdown: kramdown
